SUBJECT_BEE_SOCIAL_REGISTER = 'Bienvenido'
SUBJECT_BEE_REGISTER = 'Bienvenido: Verifica tu cuenta aqui'
SUBJECT_BEE_ACTIVATE_ACCOUNT = 'Activacion de cuenta'
SUBJECT_BEE_INACTIVATE_ACCOUNT = 'Desactivacion de cuenta'
SUBJECT_RECOVER_PASSWORD = 'Recover password'
SUBJECT_BEE_PURCHASE_AWARD = 'Informacion del premio que haz canjeado'