__author__ = 'palencia77'

# GENERAL STATUS:
STATUS_OBJECT_ACTIVE = "ACTIVE"
STATUS_OBJECT_INACTIVE = "INACTIVE"
STATUS_OBJECT_DELETED = "DELETED"
STATUS_OBJECT_SUSPENDED = "SUSPENDED"
STATUS_OBJECT_ROBOT = "ROBOT"
STATUS_OBJECT_PENDING = "PENDING"

# BEE STATUS:
STATUS_BEE_UNVERIFIED = "UNVERIFIED"
STATUS_BEE_VERIFIED = "VERIFIED"

# TOKEN STATUS:
STATUS_TOKEN_VALID = "VALID"
STATUS_TOKEN_INVALID = "INVALID"
STATUS_TOKEN_USED = "USED"

# REQUEST FRIENDSHIP:
STATUS_FRIENDSHIP_PENDING = "PENDING"
STATUS_FRIENDSHIP_ACEPTED = "ACEPTED"

# NOTIFICATION STATUS:
STATUS_NOTIFICATION_READ = "READ"
STATUS_NOTIFICATION_UNREAD = "UNREAD"

# CAUSE STATUS:
STATUS_CAUSE_SOLVED = "SOLVED"
STATUS_CAUSE_STANDBY = "STANDBY"